export const CONFIG = {
  CANVAS: { WIDTH: 800, HEIGHT: 400 },
  FPS: 60,
  PADDLE: { WIDTH: 10, HEIGHT: 100, SPEED: 8 },
  BALL: { SIZE: 10, DEFAULT_SPEED_X: 5, DEFAULT_SPEED_Y: 3, MAX_SPEED: 20 },
  PARTICLE: { LIFETIME: 30, COUNT_ON_HIT: 5 },
  COMBO: { RESET_TIME: 180, MIN_FOR_NOTIFICATION: 5 },
  LEVEL: { POINTS_PER_LEVEL: 5, DIFFICULTY_FACTOR: 0.1 }
};

export const SOUND_FREQUENCIES = {
  HIT: 440,
  SCORE: 880,
  GAMEOVER: 220,
  COMBO: 1200,
  ACHIEVEMENT: 660,
  DEFAULT: 660
};
